Install mit postgre sql
mapbender/mapbender-documentation pull request #188
Opened 2020-08-24 12:16 UTC by thzanger

The installation with PostgreSQL missed resetroot and newway to load epsg codes.

2020-09-04 06:57 UTC, rschwammborn commented on de/installation/installation_windows.rst
> +    app/console mapbender:config:check
Maybe it's useful to include `php.exe` to the command (like this: `php.exe app/console mapbender:config:check`)? Just for consistency...

2020-09-04 06:58 UTC, rschwammborn commented on en/installation/installation_windows.rst
> +    app/console mapbender:config:check
...same suggestion as in the German version of the file (`php.exe`).

2020-09-04 07:00 UTC, rschwammborn reviewed
The changes are good. I made some small in-line suggestions in the files (which are not absolutely necessary to apply, but would imo be nice to have).

2020-09-10 12:04 UTC, eschuettler commented
The line 'app/console fom:user:resetroot' has been deleted, because it was redundant information. In the documentation (where the information is needed) is a [link](https://doc.mapbender.org/en/installation/configuration.html#creating-the-administrative-user).
The link works in the German version, but I noticed that it won't work in the English version.

2020-09-10 12:06 UTC, eschuettler requested changes
The line 'app/console fom:user:resetroot' has been deleted, because it was redundant information. In the documentation (where the information is needed) is a link.
The link works in the German version, but I noticed that it won't work in the English version.

2020-09-14 13:45 UTC, eschuettler approved these changes

2020-09-15 09:31 UTC, merged