Language (behavior) fix
mapbender/mapbender-documentation pull request #315
Opened 2022-03-11 14:53 UTC by rschwammborn

1. First commit includes fixes for minor documentation language errors in the installation pages.
2. Second commit adjusts the way Mapbender's language setting is handled. Starting with Mapbender v3.3, according to https://symfony.com/doc/4.4/translation.html#fallback-translation-locales

2022-03-11 15:43 UTC, astroidex requested changes

2022-03-11 15:43 UTC, astroidex commented on de/customization/yaml.rst
> +    fallbacks:         en
is it like that? Or does mapbender take the fallback locale of the browser? Info for 3.3 documentation

2022-03-11 15:43 UTC, astroidex commented on de/customization/yaml.rst
> +Mapbender wird automatisch an die eingestellte Browsersprache angepasst.
Vielleicht eher so: Mapbender verwendet automatisch die ausgewählte Sprache der Browsereinstellungen.

2022-03-11 15:43 UTC, astroidex commented on de/customization/yaml.rst
>  Weitere Informationen unter http://doc.mapbender.org/en/book/translation.html
Please change the link to https://doc.mapbender.org/en/architecture/translation.html (book/... is the old link

2022-03-11 15:43 UTC, astroidex commented on en/architecture/translation.rst
> +Moreover, you can set the following parameter to your preferred language in the configuration file **app/config/parameters.yml**. If a translation should be missed, the set language instead will be u
...the defined langauge will be used.

See comment above. Check with dev the behaviour

2022-03-11 15:43 UTC, astroidex commented on de/customization/yaml.rst
> +    fallbacks:         en
Does it change to 

fallbacks: ['en']

2022-03-11 15:43 UTC, astroidex commented on en/installation/installation_configuration.rst
>  and should only be available from localhost.
default is only localhost. But you could edit the file at web/app_dev.php and add more IPs for further access

2022-03-14 13:52 UTC, rschwammborn commented
Hi @astroidex , I took your comments in https://github.com/mapbender/mapbender-documentation/pull/315/commits/f59f456fa2baaea4e1d56ccd631998b63a02155f into account , please check again if everything is good.

2022-03-17 12:30 UTC, rschwammborn commented
Please note that the base branch of this PR should be the upcoming 3.3 documentation, since new features are documented. I therefore changed the PR into a draft. Branch switch will occur as soon as the new doc branch is available.

2022-09-29 08:20 UTC, astroidex commented
looks good.

2022-09-29 08:20 UTC, astroidex approved these changes

2022-09-29 08:21 UTC, merged