add shared instances to sources page
mapbender/mapbender-documentation pull request #347
Opened 2023-02-13 16:02 UTC by rschwammborn

- Add explanations about Shared Instances and the Sources Page to the docs page.
- Structure and text could be complete. Probably missing: Screenshots?

2023-02-14 07:25 UTC, astroidex requested changes

2023-02-14 07:25 UTC, astroidex commented on de/functions/backend/source.rst
> +Quellen laden
Leerzeile muss entfallen

2023-02-14 07:25 UTC, astroidex commented on de/functions/backend/source.rst
> +.. tip:: **Hinweis**: Am sinnvollsten ist es, die Datenquelle vor dem Hochladen auf ihre Richtigkeit hin zu überprüfen.
Am Sinnvollsten Groß?
Noch Hinzufügen: Dies erfolgt über den Aufruf des getCapabilities-Requests im Browser

2023-02-14 07:25 UTC, astroidex commented on de/functions/backend/source.rst
>    In der Regel verweisen OGC-WMS Capabilities auf ``xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd``. Die dort unterstützen Namensräume sin
Ist das notwendig? Würde ich weglassen.

2023-02-14 07:25 UTC, astroidex commented on de/functions/backend/source.rst
> +* **Metadaten anzeigen**: Zeigt die Metadaten eines ausgewählten Dienstes an. Öffnet einen neuen Bereich, der tabbasiert Metadaten, Mapbender-Anwendungen mit Zugriff, Kontaktinformationen, Details (z
der tabbasiert -> besser ggf. : der in mehreren Reitern

2023-02-14 07:25 UTC, astroidex commented on de/functions/backend/source.rst
> +* **Metadaten anzeigen**: Zeigt die Metadaten eines ausgewählten Dienstes an. Öffnet einen neuen Bereich, der tabbasiert Metadaten, Mapbender-Anwendungen mit Zugriff, Kontaktinformationen, Details (z
Dienstlayer -> die Layer des Dienstes

2023-02-14 07:25 UTC, astroidex commented on de/functions/backend/source.rst
> +In the metadata dialog of a specific service, it is also possible to interact with a hamburger button menu (top right) that allows:
Satz ist noch auf englisch

2023-02-14 07:25 UTC, astroidex commented on de/functions/backend/source.rst
> +* **Löschen**: Entfernt den Dienst aus Mapbender.
Ist das so? Oder nur die Freie Instanz?

2023-02-14 07:25 UTC, astroidex commented on en/functions/backend/source.rst
> +.. tip:: You should check your capabilties document in your browser before uploading the service.
Siehe de. Noch Hinweis zu getCapabilities Request

2023-02-14 07:25 UTC, astroidex commented on en/functions/backend/source.rst
> +After a successful upload, Mapbender will provide an overview of the WMS information.
upload - maybe better registration

2023-02-14 07:25 UTC, astroidex commented on en/functions/backend/source.rst
> +In general, OGC WMS Capabilities refer to ``xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd``. The supported namespaces in that schema are:
ggf. entfernen

2023-02-14 07:25 UTC, astroidex commented on en/functions/backend/source.rst
> +In the metadata dialog of a specific service, it is also possible to interact with a hamburger button menu (top right) that allows:
hamburg button menu -> ist das englisch?

2023-02-22 11:39 UTC, astroidex reviewed
Nice. Only minir comments.

2023-02-22 11:39 UTC, astroidex commented on de/functions/backend/source.rst
> +Quellen laden
Datenquelle laden

2023-02-22 11:39 UTC, astroidex commented on de/functions/backend/source.rst
> +Über den Backend-Menübereich Datenquellen können OGC WMS-Dienste in der Version 1.1.1 und 1.3.0 in Mapbender registriert werden.
Mapbender kann auch WMTS neben WMS. Bald kommen noch weitere Datenquellen hinzu. Daher dies berücksichtigen

2023-02-22 11:39 UTC, astroidex commented on en/quickstart.rst
> +#. Click on *"Load"* to upload the service in the repository.
register instead of upload ... in the Mapbender repository

2023-03-08 13:32 UTC, astroidex requested changes
Please add the getcapabilities request to osm demo to the mapbender_add_source.png to people see how a getCapabilitie request can look like

2023-03-08 13:32 UTC, astroidex commented on de/functions/backend/source.rst
> +Die Bereiche Datenquellen und Freie Instanzen listen die erfolgreich eingeladenen und konfigurierten Dienste auf:
geladenen nicht eingeladenen

2023-03-08 13:32 UTC, astroidex commented on de/functions/backend/source.rst
> +* **Datenquelle aktualisieren**: Bei Buttonklick wird der Bereich "Datenquelle aktualisieren" geöffnet, der den Service und die zugehörigen Metadaten aktualisiert.
den Dienst statt den Service

2023-03-08 13:32 UTC, astroidex commented on de/functions/backend/source.rst
> +* **Datenquelle aktualisieren**: Bei Buttonklick wird der Bereich "Datenquelle aktualisieren" geöffnet, der den Service und die zugehörigen Metadaten aktualisiert.
den Dienst

2023-03-08 13:32 UTC, astroidex commented on en/functions/backend/source.rst
> +* **Update source**: Click the button to show a new field that allows a refresh of the service and its metadata.
Make it short: Only write (suggestion)
Update service information by reload of the getCapabilities document.

2023-03-08 13:32 UTC, astroidex commented on de/functions/backend/source.rst
> +* **Datenquelle aktualisieren**: Bei Buttonklick wird der Bereich "Datenquelle aktualisieren" geöffnet, der den Service und die zugehörigen Metadaten aktualisiert.
Kurz: 
Aktualisierung der Service-Information durch erneutes Laden des getCapabilities-Dokumentes.

2023-03-08 13:32 UTC, astroidex commented on en/functions/backend/source.rst
> +* **Update source**: Click the button to show a new field that allows a refresh of the service and its metadata.
see above. Text suggestion

2023-03-13 14:31 UTC, rschwammborn commented
Implemented all the change requests. Strangely, I cannot find the conflicts that should be resolved in the mentioned files - neither in web nor in IDE..maybe someone with authorization could check if everything's good here (or not).

2023-03-27 11:43 UTC, astroidex approved these changes

2023-05-05 06:24 UTC, merged