Add WMS reload section to sources.rst
mapbender/mapbender-documentation pull request #365
Opened 2023-04-17 10:27 UTC by rschwammborn

- Adds a first draft for the WMS reload section (enhances PR #361) 
- (In addition: Removes text errors from `migration.rst`)

2023-04-24 07:10 UTC, astroidex reviewed
Sollen ebi Datenqiuelle aktualsieren auch schon die neuen Checkboxen rein? Oder in einem nächsten PR?

2023-04-24 07:10 UTC, astroidex commented on de/functions/backend/sources.rst
> +Die Aktualisierung einer Datenquelle erfolgt zunächst über den Aufruf die Seite Datenquellen im Backend. Nachdem Sie den gewünschten Dienst in der Liste gefunden haben, betätigen Sie den Aktualisiere
der Seite Datenquellen -> nicht die Seite

2023-04-24 07:56 UTC, rschwammborn commented on de/functions/backend/sources.rst
> +Die Aktualisierung einer Datenquelle erfolgt zunächst über den Aufruf die Seite Datenquellen im Backend. Nachdem Sie den gewünschten Dienst in der Liste gefunden haben, betätigen Sie den Aktualisiere
Gute Idee, ich schiebe noch einen Commit mit den neuen Checkboxen hinterher.

2023-04-25 07:34 UTC, astroidex requested changes
Screenshots gerne auch mit getCapabilities URL
Checkboxen mit den neuen Möglichkeiten fehlen auf den Screensots
Im Text fehlt noch die Info, dass ein Layerset im Map-Element noch aktiviert werden muss

2023-04-25 07:34 UTC, astroidex commented on de/functions/backend/sources.rst
> +Über die Datenquellen können Sie OGC-WMS Dienste in der Version 1.1.1 und 1.3.0 in Mapbender registrieren. Informationen zum Einbinden von Diensten und der Nutzung in Mapbender finden Sie im `Quickst
WMTS geht ja auch

2023-04-25 07:34 UTC, astroidex commented on de/functions/backend/sources.rst
> +* **Typ**: Vordefinierte Datentypauswahl (OGC WMS bzw. OGC WMTS / TMS).
Auswahl des Typs der Datenquelle

2023-04-25 07:34 UTC, astroidex commented on de/functions/backend/sources.rst
> +In der Regel verweisen OGC-WMS Capabilities auf ``xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd``. Die dort unterstützen Namensräume sind:
Kann entfallen, oder? Ist nicht relevant

2023-04-25 07:34 UTC, astroidex commented on de/functions/backend/sources.rst
> +Dadurch öffnet sich die Aktualisierungsmaske. Hier können Sie die URL oder Benutzername / Passwort des Dienstes aktualisieren.
anpassen -> statt aktualisieren

2023-04-25 07:34 UTC, astroidex commented on de/functions/backend/sources.rst
> +* **Neu hinzugefügte Layer auswählen**: Ist der Haken an dieser Checkbox gesetzt, werden durch die Aktualisierung neu geladene Dienst-Layer automatisch in Anwendungen sichtbar. Hinweis: Zur Anzeige i
Hinweis: Zur Anzeige im Kartenbereich müssen sie zusätzlich aktiviert werden. -> Satz stimmt so nicht. Wenn die Checkbox aktiv ist, müssen sie nicht noch aktiviert werden.

vielleicht besser:
neu geladene Dienst-Layer automatisch in Anwendungen auswählbar und sind aktiv. Dazu muss allerdings auch **Neu hinzugefügte Layer aktivieren** gesetzt sein. Ist **Neu hinzugefügte Layer auswählen** nicht gesetzt erscheint der Layer im Ebenenbaum, ist aber nicht aktiviert.

2023-04-25 07:34 UTC, astroidex commented on de/functions/backend/sources.rst
> +* **Neu hinzugefügte Layer aktivieren**: Ist der Haken an dieser Checkbox gesetzt, werden durch die Aktualisierung neu geladene Dienst-Layer automatisch in eingebundenen Anwendungen aktiv.
Ist **Neu hinzugefügte Layer aktivieren** nicht gesetzt, erscheint der neue Layer nicht im Ebenenbaum.

2023-04-25 07:34 UTC, astroidex commented on de/functions/backend/sources.rst
> +Sofern die Datenquelle nicht aktualisiert werden soll, kann der ``Abbrechen``-Button genutzt werden, um alle getätigten Änderungen zu verwerfen.
muss Abbbrechen erläutert werden?

2023-04-25 07:34 UTC, astroidex commented on de/functions/backend/sources.rst
> +Falls die Änderungen vorgenommen werden sollen, klicken Sie auf den ``Laden``-Button, um die Datenquelle zu aktualisieren. Die aktualisierte Version wird anschließend in den Konfigurationseinstellung
...Datenquelle zu aktualisieren. Dabei wird das getCapabilities-Dokument neu ausgelesen.

Die aktualisierte Version wird anschließend in den Konfigurationseinstellungen angezeigt und Änderungen werden in Anwendungen, in denen der Dienst verwendet wird angewandt.

2023-04-25 07:34 UTC, astroidex commented on de/functions/basic/layertree.rst
>  Über den Reiter **Layerset** können Layersets definiert und Layer in eine Anwendung eingebunden werden.
Layer -> besser: Dienste oder Datenquellen

2023-04-25 07:34 UTC, astroidex commented on de/functions/basic/layertree.rst
> +          Backend-Konfiguration des thematischen Layertrees.
Backend-Konfiguration des thematischen Layertrees. -> besseer. Backend-Konfiguration Thematische Layer

2023-04-25 07:34 UTC, astroidex commented on de/functions/basic/layertree.rst
>  Wenn wir im Themenset “World” die Standardeinstellungen beibehalten und im Themenset “Project NRW” die anderen Optionen aktivieren, sieht die Konfiguration des Elements wie folgt aus:
Themenset? -> Besser Layerset?

2023-04-25 07:34 UTC, astroidex commented on de/functions/basic/layertree.rst
>  Wir haben die Layersets somit als thematische Gruppen in den Ebenenbaum eingebunden. Durch die Konfiguration der thematischen Layer stellt sich der Layertree in der Anwendung nun wie folgt dar:
t sich der Layertree in der An .--> Ebenenbaum

2023-04-25 07:34 UTC, astroidex commented on de/functions/basic/layertree.rst
>  #. Einrichtung des Layertrees selbst
Layertree -> Ebenenbaum

2023-05-05 06:44 UTC, merged