Add 3.3.4 migration instructions
mapbender/mapbender-documentation pull request #367
Opened 2023-04-17 15:22 UTC by rschwammborn

Manual migration information, as seen in [changelog](https://github.com/mapbender/mapbender/blob/master/CHANGELOG.md).

2023-04-17 16:32 UTC, Phocacius commented on en/installation/migration.rst
> +* Next, you need to add a CSRF token in ``security.yml``. Configure the ``form_login`` settings as follows:
the line does not by itself add a CSRF token, but configures them to be used, so the wording is a bit inaccurate.

Suggestion: You need to configure CSRF tokens to be used during login by adding the following line in `security.yml`.

If possible (I never used rst myself), print  the last line as bold text.

2023-04-17 16:32 UTC, Phocacius commented on en/installation/migration.rst
> +* For productive environments, it is important to install an SSL certificate. After that, set the ``parameters.cookie_secure`` variable in your ``parameters.yml`` to ``true``. This ensures that the L
Also add this in the configuration section of the regular user guide (not only the migration). Doesn't hurt to mention it in the migration as well though :)

2023-04-18 08:42 UTC, rschwammborn commented on en/installation/migration.rst
> +* For productive environments, it is important to install an SSL certificate. After that, set the ``parameters.cookie_secure`` variable in your ``parameters.yml`` to ``true``. This ensures that the L
Right! Added SSL info to yaml.rst.

2023-04-18 08:45 UTC, rschwammborn commented on en/installation/migration.rst
> +* Next, you need to add a CSRF token in ``security.yml``. Configure the ``form_login`` settings as follows:
I took your text suggestion and added a **reference** above the code section, see my commit below.

2023-04-18 08:50 UTC, Phocacius approved these changes

2023-04-18 09:02 UTC, astroidex requested changes

2023-04-18 09:02 UTC, astroidex commented on en/customization/yaml.rst
> +To configurate the database the files config.yml and parameters.yml are needed. The file config.yml contains placeholders for variables, which are specified in the file parameters.yml. For the defaul
see german version. Bitte auch anpassen

2023-04-18 09:02 UTC, astroidex commented on en/installation/migration.rst
> +    $ app/console doctrine:schema:update --force
$ kann weggelassen werden

2023-04-18 09:02 UTC, astroidex commented on en/installation/migration.rst
> +* Next, you need to configure CSRF tokens to be used during login by adding **csrf_token_generator: security.csrf.token_manager** to the form_login section in ``security.yml`` as follows:
If you use the acutual code the section is already added to the security.yml file

2023-04-26 09:30 UTC, astroidex approved these changes

2023-05-03 11:02 UTC, merged