Fixes to layerset, quickstart, sketch and sources pages
mapbender/mapbender-documentation pull request #370
Opened 2023-05-08 10:48 UTC by rschwammborn

Small PR with URL path, wording and screenshot updates ("quality control").
Fixes some errors that went into main branch via the latest merges (#365-#368).

2023-05-08 12:21 UTC, astroidex requested changes

2023-05-08 12:21 UTC, astroidex commented on en/functions/backend/layerset.rst
> +- or by work with the possibilities of the `thematic layer tree <../basic/layertree>`_, to create different layersets and distribute the basic services and thematic services in them to place them in
better: 
- or by work with the possibilities of the `thematic layer tree <../basic/layertree>`_. This option will show the layerset name with a folder and checkbox in the layertree. You can define whether the layerset folder should be shown and whether it should be opened on start.

2023-05-08 12:21 UTC, astroidex commented on en/functions/backend/layerset.rst
> +In a layerset instance, vendor specific parameters are appended to the WMS request. The implementation follows the specifications of the multi-dimensional data in the WMS specification. In Mapbender,
In a layerset instance -> In a service instance (NOT layerset instance)

2023-05-08 12:21 UTC, astroidex commented on en/functions/backend/layerset.rst
> +In a layerset instance, vendor specific parameters are appended to the WMS request. The implementation follows the specifications of the multi-dimensional data in the WMS specification. In Mapbender,
Shall we delete the sentence? I do not get the meaning.
The implementation follows the specifications of the multi-dimensional data in the WMS specification.

2023-05-08 12:21 UTC, astroidex commented on en/functions/backend/layerset.rst
>  * Layersets can be switched on or off for a map completely in the `Map element <../basic/map>`_ settings.
Layersets can be switched on or off for a map completely
--> better: Layersets be disabled for the application in the `Map element <../basic/map>`_ settings.

2023-05-08 12:21 UTC, astroidex commented on en/quickstart.rst
> +Applications can be re-edited at any point. In order to do so, navigate to the application overview. Here, you can click on a |mapbender-button-edit| ``Button`` for every application with correspondi
maybe delete at any point.

2023-05-09 08:15 UTC, rschwammborn commented
Closing this because I didn't check out a clean new branch while working on #371. The mentioned PR carries all changes made here (+ edits from change requests) and can be used as replacement.

2023-05-09 08:15 UTC, closed without merging