Tidy up URL parameter section, fix broken crosslink
mapbender/mapbender-documentation pull request #413
Opened 2023-11-14 12:40 UTC by rschwammborn

2023-11-28 07:23 UTC, astroidex requested changes

2023-11-28 07:23 UTC, astroidex commented on en/elements/basic/map.rst
> +If you have two layers that are not visible by default, put the two values of layerid and serviceid into the URL and seperate them by a comma.
layerid and serviceid - why not InstanceID and InstanceLayerId

2023-11-28 07:23 UTC, astroidex commented on de/elements/basic/map.rst
> +Wenn Sie zwei per Voreinstellung nicht sichtbare Layer haben, fügen Sie beide Werte von layerid und serviceid in die URL und trennen diese mit einem Komma.
layerid and serviceid - why not InstanceID and InstanceLayerId

2023-11-28 07:23 UTC, astroidex commented on en/quickstart.rst
> +    * ID: ID of the layer. Can be useful :ref:`to control <layer_visibility>` URL parameters.
id or InstanceLayerId?

2024-01-08 10:32 UTC, astroidex approved these changes

2024-01-08 10:33 UTC, astroidex commented on en/quickstart.rst
> +    * ID: ID of the layer. Can be useful :ref:`to control <layer_visibility>` URL parameters.
@rschwammborn should we change this in the 3.3.x version too?

2024-01-08 10:40 UTC, merged

2024-01-08 10:43 UTC, rschwammborn commented on en/quickstart.rst
> +    * ID: ID of the layer. Can be useful :ref:`to control <layer_visibility>` URL parameters.
@astroidex I'm not sure, why should this be necessary? I think it's fine for 3.3.x versions. Instead, we should specify the name of the general id for 4 and ongoing - the current hover text is rather confusing...

![layer-id-terminology](https://github.com/mapbender/mapbender-documentation/assets/21199730/c8f7bf76-47bd-4b32-adfc-e24babdc6b93)