Update TOC structure for Share
mapbender/mapbender-documentation pull request #427
Opened 2024-03-04 11:35 UTC by rschwammborn

To reduce Sphinx building errors, Share has been updated:

1. Update of Share TOC to give each file a toctree link
2. Fix a typo in filename of `persistent_map_view.rst`
3. Unrelated: Remove bullet point formatting error

2024-03-11 12:38 UTC, astroidex commented on de/elements/share.rst
>  =====
Shall we add a german title? Or a mix

2024-03-11 12:38 UTC, astroidex commented on en/elements/share/share_overview.rst
> +Next, we will explore functions which fall under the category of 'Share' as they streamline collaborative work within Mapbender applications.
shorten sentence and and adopt de translation

2024-03-11 12:38 UTC, astroidex commented on en/elements/share/share_overview.rst
> +Introduction
add Share to heading: Introduction Share

2024-03-11 12:38 UTC, astroidex commented on de/elements/share/share_overview.rst
> +Überblick
add Share to heading: Übersicht Teilen?

2024-04-22 09:04 UTC, astroidex requested changes

2024-04-22 09:04 UTC, astroidex commented on de/elements/share/share_overview.rst
> +.. note:: Folgende Eigenschaften werden nicht in der URL hinterlegt: Layer-Auswahl, Layer-Sortierung, temporäre Geometrien, Laufzeitergänzungen, Transparenz, sowie interaktiv hinzugefügte Instanzen.
wird die Layerauswahl nicht bei ShareUrl übergeben

2024-04-22 09:04 UTC, astroidex commented on en/elements/share/share_overview.rst
> +* :ref:`applicationswitcher` enables cross-application switches,
easy cross-applications switches

2024-04-22 09:04 UTC, astroidex commented on en/elements/share/share_overview.rst
> +* :ref:`persistent_map_view` simplifies the application compatibility with the web browser.
see above translation

2024-04-22 09:04 UTC, astroidex commented on en/elements/share/share_overview.rst
> +Moreover, certain map view parameters are automatically contained in every application URL.
passed instead of contained?

2024-04-22 09:54 UTC, rschwammborn commented on de/elements/share/share_overview.rst
> +.. note:: Folgende Eigenschaften werden nicht in der URL hinterlegt: Layer-Auswahl, Layer-Sortierung, temporäre Geometrien, Laufzeitergänzungen, Transparenz, sowie interaktiv hinzugefügte Instanzen.
Stimmt, es sind die temporären Änderungen in der Anwendung, die nicht via URL übermittelt werden. Ist nun klarer formuliert.

2024-04-22 10:01 UTC, astroidex requested changes

2024-04-22 10:01 UTC, astroidex commented on de/elements/share/share_overview.rst
>  ===========================
too long

2024-04-25 11:44 UTC, astroidex requested changes
please check

2024-04-25 11:54 UTC, merged