Clone description fix + Update of database configuration
mapbender/mapbender-documentation pull request #428
Opened 2024-03-06 14:58 UTC by rschwammborn

This PR fixes the wrong description of app cloning behaviour (_imp from yaml, _db from database).

Moreover, it implements the database configuration changes to the documentation which were added via [mapbender-starter PR #117](https://github.com/mapbender/mapbender-starter/pull/117)

2024-04-22 10:01 UTC, astroidex requested changes

2024-04-22 10:01 UTC, astroidex commented on en/installation/installation_configuration.rst
> +* by overriding the value in a `.env.local` file,
in an

2024-04-22 10:01 UTC, astroidex commented on en/quickstart.rst
> +* by overriding the value in a `.env.local` file,
in an

2024-05-06 10:59 UTC, rschwammborn commented on de/customization/commands.rst
> +Eine Anwendung kann als JSON- oder YAML-Datei exportiert werden. Dabei muss der Anwendungs-URL-Titel (slug) angebeben werden und eine Exportdatei definiert werden.
Das geht noch (nur mit dem Kommando). Ist nun explizit klargestellt, dass dem so ist.

2024-05-06 11:01 UTC, rschwammborn commented on en/customization/yaml.rst
>  The following Configuration files are under application/config.
Teils teils. Habe eine Formulierung gefunden, die beides einschließt.

2024-05-06 14:09 UTC, astroidex requested changes
Satz kann raus: Die Sitelinks werden mittels "|" voneinander getrennt.

2024-05-06 14:09 UTC, astroidex commented on de/customization/yaml.rst
> +Die Datenbankkonfiguration in der `.env` sieht wie folgt aus, wenn eine Suchdatenbank via PostgreSQL referenziert wird:
.env.local

2024-05-06 14:09 UTC, astroidex commented on de/customization/yaml.rst
>  Mit Mapbender können Sie auch mehrere Datenbanken verwenden. Dies wird empfohlen, wenn Sie Ihre eigenen Daten von den Mapbender-Daten trennen möchten. Das kann nützlich sein, wenn Sie eigenen Code ve
empfohlen. Die Geodaten sollten getrennt von der Mapbender-Datenbank liegen.

2024-05-06 14:09 UTC, astroidex commented on de/customization/yaml.rst
>  Mit Mapbender können Sie auch mehrere Datenbanken verwenden. Dies wird empfohlen, wenn Sie Ihre eigenen Daten von den Mapbender-Daten trennen möchten. Das kann nützlich sein, wenn Sie eigenen Code ve
Kann weg: Das kann nützlich sein, wenn Sie eigenen Code verwenden, der nicht zu einem Mapbender-Bundle gehört.

2024-05-06 14:09 UTC, astroidex commented on de/customization/yaml.rst
> +Wenn Sie eine weitere Datenbank verwenden möchten, müssen Sie eine zweite Datenbankverbindung mit einem anderen Namen in der `.env`-Datei definieren.
.env.local

2024-05-06 14:09 UTC, astroidex commented on de/customization/yaml.rst
> +In den Elementen :ref:`search_router_de` und :ref:`digitizer_de` kann nun auf die Datenbankverbindung (connection) mit dem Namen *search_db* verwiesen werden.
Was sind das für refs?

2024-05-06 14:09 UTC, astroidex commented on de/customization/yaml.rst
> +Die Mailerangaben werden in der `.env.local` Datei über eine Umgebungsvariable in der `fom.yaml` eingetragen.
Die Angabe zum Mailer wird in der `.env.local` Datei über die Varibale MAILER_DSN definiert.

2024-05-06 14:09 UTC, astroidex commented on de/customization/yaml.rst
> +Standard- und Beispielkonfiguration (auskommentiert) in der `.env.local`:
Satz kann weg

2024-05-06 14:09 UTC, astroidex commented on de/customization/yaml.rst
>  Disclaimer
Disclaimer geibt es nicht mehr oder?

2024-06-10 07:54 UTC, astroidex approved these changes

2024-06-10 10:07 UTC, merged