Add enhancement to URL layer visibility syntax
mapbender/mapbender-documentation pull request #432
Opened 2024-04-15 10:29 UTC by rschwammborn

This resolves #431 , it

- adds the enhanced feature,
- adds a new screenshot,
- adds a new example,
- fixes wording issues.

2024-04-22 10:21 UTC, astroidex requested changes

2024-04-22 10:21 UTC, astroidex commented on de/elements/basic/map.rst
> +  ?visiblelayers=<InstanceID>/<InstanceLayerID>
ggf. noch einbauen - so in der Art
Notice: Bitte beachten Sie, dass die IDs eines Dienstes nach jedem Update des Dienstes ändern. Die Übergabe des Names erscheint daher als langlebiger.

2024-04-22 10:21 UTC, astroidex commented on de/elements/basic/map.rst
> +Sie können bestimmte Ebenenattribute mit dem URL-Parameter ``visiblelayers`` übermitteln, um diese in der Startansicht zu aktivieren:
Mapbender ermöglich via ``visiblelayers`` die Möglichkeit, Layer schon beim Start einer Anwendung zu aktivieren. Hierbei kann die Aktivierung entweder via ID oder Name erfolgen.

2024-04-22 10:21 UTC, astroidex commented on de/elements/basic/map.rst
> +* <SourceName>
ggf. direkt die Parameter in eine Zeile schreiben
```

* <SourceName>/<LayerName>
* <InstanceID>/<InstanceLayerID>
```

2024-04-22 10:21 UTC, astroidex commented on de/elements/basic/map.rst
> +Um die Attributwerte anzuzeigen, gibt es im Layerset-Tab einer Anwendung neben jedem Layer ein Icon mit drei Punkten.
Um weitere Eigenschaften eines Layers anzuzeigen, gibt es im Layerset-Reiter bei der Instanz-Konfiguration neben jedem Layer ein Icon mit drei Punkten.

2024-04-22 10:21 UTC, astroidex commented on de/elements/basic/map.rst
> +Im zweiten Textfeld stehen entweder Source- oder Layername, je nachdem, ob die Instanz selbst oder ein Layer über das Drei-Punkte-Menü angewählt wurde.
entweder Source- oder Layername -> ist das nicht das selbe?
würde schreiben
Im zweiten Textfeld steht der Layername. Dabei wird in der ersten Zeile der Root-Layername (SourceName) ausgegeben. 

oder wollen wir direkt SourceName -> ersetzen durch RootLayerName

2024-04-22 10:21 UTC, astroidex commented on de/elements/basic/map.rst
> +Wenn Sie mehr als einen Punkt im Aufruf übermitteln, zoomt die Karte auf 150 % der Gesamt-Boundingbox.
ist das so? Was ist damit gemeint 150%

2024-04-22 10:21 UTC, astroidex commented on de/elements/basic/map.rst
> +Punkte übertragen
übergeben oder übertragen/übermitteln?
Ich finde übergeben ganz gut. Kann gerne immer gleich sein

2024-04-22 10:21 UTC, astroidex commented on en/elements/basic/map.rst
> +Making layers visible
Making layers visible -> better: Activate Layer

see above de version

2024-04-22 10:21 UTC, astroidex commented on figures/wms_visiblelayers_attributevalues.png
Better make a screenshot of the whole dialog with all the parmaters and the maybe the table in the baclground too (?)

2024-04-25 11:29 UTC, rschwammborn commented on de/elements/basic/map.rst
> +Im zweiten Textfeld stehen entweder Source- oder Layername, je nachdem, ob die Instanz selbst oder ein Layer über das Drei-Punkte-Menü angewählt wurde.
SourceName heißt jetzt RootLayerName. Das war eine gute Idee, weil das die Begriffe der Kategorien ID (verknüpft mit dem Wort Source) und Name (verknüpft mit dem Wort Layer) besser voneinander abgrenzt.

2024-04-25 11:44 UTC, astroidex requested changes

2024-04-25 12:19 UTC, merged