Add data-upload element
mapbender/mapbender-documentation pull request #436
Opened 2024-04-22 13:58 UTC by a12e24

#429 this adds the new data upload into the mapbender documentation.

2024-04-24 11:14 UTC, astroidex requested changes

2024-05-06 12:54 UTC, rschwammborn approved these changes

2024-05-06 13:44 UTC, astroidex requested changes

2024-05-06 13:44 UTC, astroidex commented on de/elements/basic/dataupload.rst
> +Daten Laden
Daten laden

2024-05-06 13:44 UTC, astroidex commented on de/elements/basic/dataupload.rst
> +Mit dem Element *Daten Laden* können Punkte, Linien, Polygone und Multipolygone aus Geodaten in Mapbender hochgeladen werden.
Daten laden -> kleines L

können Geodaten in den Formaten GeoJSON-, KML-, GML- und GPX geladen werden.

2024-05-06 13:44 UTC, astroidex commented on de/elements/basic/dataupload.rst
> +Sie können Dateien im GeoJSON-, KML-, GML- und GPX-Format per Drag and drop oder mithilfe des Ordnersystems der Dateiverwaltung hochladen.
Sie können ein bis mehrere Dateien per drag & drop oder durch Auswahl aus dem Dateisystem hochladen.

2024-05-06 13:44 UTC, astroidex commented on de/elements/basic/dataupload.rst
> +.. hint:: Die Dateigröße sollte 10 MB nicht überschreiten. Diese Einstellung kann in der YAML-Definition angepasst werden.
In der Elementkonfiguration kann eine maximale Dateigröße definiert werden.

2024-06-10 07:51 UTC, astroidex approved these changes

2024-06-10 07:51 UTC, astroidex approved these changes

2024-06-10 10:07 UTC, merged