add sidepane option, user-selectable and screenshot for Ruler element
mapbender/mapbender-documentation pull request #449
Opened 2024-06-10 11:55 UTC by momotosushi

This PR changes the Ruler element documentation as in #446 requested

2024-06-10 12:39 UTC, astroidex requested changes
Please also add the new type to the yaml definition type: both

2024-06-10 12:39 UTC, astroidex commented on de/elements/basic/ruler.rst
> +Mit dem Lineal wird eine Geometrie gezeichnet, deren Länge oder Flächeninhalt berechnet wird. Das Element kann in der Sidepane oder mit einem :ref:`button_de` verwendet werden.
Besser: Mit dem Messen-Werkzeug wird eine ..

2024-06-10 12:39 UTC, astroidex commented on en/elements/basic/ruler.rst
> +Selecting a type determines whether the element measures lines or areas or whether the user makes the selection.
or whether both options are offered and the user can make the selection in the client.

2024-06-10 12:39 UTC, astroidex commented on de/elements/basic/ruler.rst
> +Durch die Auswahl eines Typs wird bestimmt, ob das Element Linien oder Flächen misst oder der Benutzer die Auswahl trifft.
oder beides und so der Benutzer die Auswahl im Client treffen kann.

2024-06-11 07:20 UTC, momotosushi commented on en/elements/basic/ruler.rst
> +Selecting a type determines whether the element measures lines or areas or whether the user makes the selection.
Done

2024-06-11 07:20 UTC, momotosushi commented on de/elements/basic/ruler.rst
> +Durch die Auswahl eines Typs wird bestimmt, ob das Element Linien oder Flächen misst oder der Benutzer die Auswahl trifft.
Done

2024-06-11 07:20 UTC, momotosushi commented on de/elements/basic/ruler.rst
> +Mit dem Lineal wird eine Geometrie gezeichnet, deren Länge oder Flächeninhalt berechnet wird. Das Element kann in der Sidepane oder mit einem :ref:`button_de` verwendet werden.
Done

2024-06-11 07:22 UTC, momotosushi commented
YAML Teil überarbeitet und Fomulierungsänderungen durchgeführt

2024-06-11 07:23 UTC, merged