New Screenshots for Activity Indicators
mapbender/mapbender-documentation pull request #453
Opened 2024-06-13 10:46 UTC by momotosushi

2024-06-13 10:48 UTC, astroidex requested changes
add new image for activity indicator in a application

2024-06-13 11:00 UTC, astroidex requested changes
en version is not visible at the bootom

2024-06-13 12:51 UTC, rschwammborn approved these changes

2024-06-13 12:51 UTC, rschwammborn reviewed
Looks good to me.

2024-06-14 06:05 UTC, astroidex approved these changes

2024-06-14 06:05 UTC, merged