Simple search duplication section
mapbender/mapbender-documentation pull request #493
Opened 2024-07-25 11:55 UTC by rschwammborn

Adds the duplication feature to the simple search pages.

2024-07-25 13:04 UTC, astroidex requested changes

2024-07-25 13:04 UTC, astroidex commented on de/elements/search/simplesearch.rst
> +Duplizieren einer Einfachen Suchkonfiguration
Duplizieren einer Suchkonfiguration (ohne einfachen)

2024-07-25 13:04 UTC, astroidex commented on en/elements/search/simplesearch.rst
> +Duplicate a simple search configuration
Duplicate a search configuration

2024-07-25 13:04 UTC, astroidex commented on en/elements/search/simplesearch.rst
> +It is possible to duplicate a search form in the backend configuration window:
The element can handle multiple search confirgurations.
It is possible to duplicate a search form in the backend configuration window:

2024-07-25 13:04 UTC, astroidex commented on de/elements/search/simplesearch.rst
> +Es ist möglich, ein Suchformular im Backend-Konfigurationsfenster zu duplizieren:
Das Element unterstützt mehrere Suchkonfigurationen.

2024-07-25 13:04 UTC, astroidex commented on figures/de/simplesearchduplication.png
It would be nicer to say Address search and Search Parcel as example. Bzw. Adresssuche und Flrustückssuche

2024-07-25 13:07 UTC, astroidex commented
- ggf. noch angeben. dass die Suchen via drag and drop in der reihenfolge verschoben werden können
- ggf. im screenshot zwei Konfigurationen nebeneinander: 1x nur 1 Suche, 1x mit meheren 
- https://doc.mapbender.org/_images/simplesearch.png

2024-07-29 09:17 UTC, rschwammborn commented
Screenshots were updated, hint to drag and drop was added.

2024-07-29 09:47 UTC, momotosushi approved these changes

2024-08-22 12:32 UTC, merged